### ISSUE TITLE
Not work on IDA 8.3

### ISSUE THREAD

**Issue by outdever** [yshestakov/ida_proc_1801#6]
When analizing got error:
`Exception in ida_idp.IDP_Hooks dispatcher function: SWIG director method error. Error detected when calling 'IDP_Hooks.ev_out_header'
Traceback (most recent call last):
  File "D:\IDA Pro 8.3 (x86, x86_64)\python\3\ida_idp.py", line 7804, in ev_out_header
    return self._get_notify("out_header", imp_forced_val=1)(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IDA Pro 8.3 (x86, x86_64)\python\3\ida_idp.py", line 7737, in f
    meth(*args)
  File "D:/IDA Pro 8.3 (x86, x86_64)/procs\k1801vm1.py", line 741, in notify_out_header
    for opcode, itype in self.bm1_cmd.iteritems():
                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'iteritems'`

**Comment by yshestakov** [comment]
@outdever thanks. `.iteritems()` is not compatible with Python3. So, I replaced it by `.items()` in the #7

**Comment by outdever** [comment]
it worked
